config/routes.rb
Mastermind::Application.routes.draw do
  root :to => "mastermind#index", :via => :get
  devise_for :users
  match '/leaders' => 'mastermind#leaders', :via => :get
  match '/play' => 'mastermind#play', :via => :get
  match '/guess' => 'mastermind#guess', :via => :post
  

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :code, :won, :finished

  belongs_to :user, :autosave => true
  has_many :guesses, :dependent => :destroy, :autosave => true, :after_add => Proc.new { |game|
    game.user.guesses_count = game.user.guesses_count + 1
    game.guesses_count = game.guesses_count + 1
  }

  before_save :finish, :if => Proc.new { |game| game.guesses.count >= 8 }

  def guess(suggested)
    matches = Codebreaker.new(code).guess(suggested)
    if matches == code.size
      self.won = true
      finish 
    end
    guess = self.guesses.create! :code => suggested, :matches => matches
    save!
    guess
  end

  private

  def finish
    self.finished = true
    if self.won?
      self.user.games_won = self.user.games_won + 1
    else
      self.user.games_lost = self.user.games_lost + 1
    end
    self.user.save!
  end
end

app/models/guess.rb
class Guess < ActiveRecord::Base
  attr_accessible :code, :matches

  belongs_to :game, :autosave => true, :counter_cache => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :games_won, :games_lost, :games_count, :guesses_count

  has_many :games, :dependent => :destroy, :autosave => true, :after_add => Proc.new { |user| user.games_count = user.games_count + 1 }
  has_one :current_game, :class_name => Game.name, :conditions => "finished = 'f'"

  def play(code)
    game = games.create! :code => code
    save!
    game
  end

  def guesses_count_average
    (self.guesses_count.to_f / self.games_count.to_f).round(2)
  end

  class << self
    def find_top_ten
      order('games_won DESC, games_lost ASC, guesses_count ASC').limit(10)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mastermind_controller.rb
class MastermindController < ApplicationController
  before_filter :authenticate_user!, :only => [:play, :guess]
  before_filter :initialize_game, :only => [:play, :guess]

  def index
    if user_signed_in?
      @user = current_user
      render :action => "dashboard"
    end
  end

  def leaders
    @leaders = User.find_top_ten
  end

  def play
  end

  def guess
    @guess = @game.guess(request[:guess].values.join)
    render :action => "play"
  end

  private

  def initialize_game
    @game = current_user.current_game || current_user.play(make_code)
  end

  def make_code
    Codemaker.new(Rails.application.config.pegs, Rails.application.config.colors).make
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mastermind_helper.rb
module MastermindHelper
  def guess_input_tag(name, n, max=2, options = {})
    raw(n.times.collect do |n|
      select_tag("#{name}[#{n}]", options_for_select(max.times.collect), options)
    end.join)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mastermind</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <ul class="menu">
    <li><%= link_to((user_signed_in? ? 'Dashboard' : 'Home'), root_path) %></li>
    <%= render 'devise/menu/registration_items' %>
    <%= render 'devise/menu/login_items' %>
    <li><%= link_to('Leader board', leaders_path) %></li>
  </ul>
  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  <%- end -%>

<%= yield %>

</body>
</html>

app/views/leaders/index.html.erb
<h1>Leader board</h1>
<table>
  <caption>Leader board</caption>
  <thead>
    <tr>
      <th>Email</th>
      <th>Wins</th>
      <th>Loses</th>
      <th>ANG</th>
    </tr>
  </thead>

  <tbody>
    <% @leaders.each do |leader| %>
    <tr>
      <td><%= leader.email %></td>
      <td><%= leader.games_won %></td>
      <td><%= leader.games_lost %></td>
      <td><%= leader.average_guess_count %></td>
    </tr>
    <% end %>
  </tbody>

  <tfoot>
    
  </tfoot>
</table>

app/views/mastermind/dashboard.html.erb
<h1>Dashboard</h1>
<table>
  <caption>My Games</caption>
  <thead>
    <tr>
      <th>Number</th>
      <th>Guesses</th>
      <th>Result</th>
    </tr>
  </thead>

  <tbody>
    <% @user.games.each do |game| %>
    <tr>
      <td><%= game.id %></td>
      <td><%= game.guesses_count %></td>
      <td><%= game.won? ? 'won' : 'lost' %></td>
    </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="4">
        <%= link_to('Play', play_path) %>
      </td>
    </tr>
  </tfoot>
</table>

app/views/mastermind/index.erb
<h1>Welcome to Mastermind</h1>

<p>To continue, please <%= link_to 'log in', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %></p>

app/views/mastermind/index.html.erb
<h1>Welcome to Mastermind</h1>

<p>To continue, please <%= link_to 'log in', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %></p>

app/views/mastermind/leaders.html.erb
<h1>Leader board</h1>
<table>
  <caption>Leader board</caption>
  <thead>
    <tr>
      <th>Email</th>
      <th>Wins</th>
      <th>Loses</th>
      <th>ANG</th>
    </tr>
  </thead>

  <tbody>
    <% @leaders.each do |leader| %>
    <tr>
      <td><%= leader.email %></td>
      <td><%= leader.games_won %></td>
      <td><%= leader.games_lost %></td>
      <td><%= leader.guesses_count_average %></td>
    </tr>
    <% end %>
  </tbody>

  <tfoot>
    
  </tfoot>
</table>

app/views/mastermind/play.html.erb
<h1>Game</h1>
<% if @game.finished? %>
  <% if @game.won? %>
    <p>Congratulations, you won!</p>
  <% else %>
    <p>You lost, the code was <%= @game.code %></p>
  <% end %>
  <p><%= link_to('Play again?', play_path) %></p>
<% else %>
  <% if @guess %>
  <p>You guessed <%= @guess.matches %> pegs</p>
  <% end %>
  <p>Enter your guess:</p>

  <%= form_tag('/guess', :method => "post") do %>
    <%= guess_input_tag('guess', Rails.application.config.pegs, Rails.application.config.colors) %>
    <%= submit_tag("Guess") %>
  <% end %>
<% end %>